name: Branch Protection
on: push
jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set Branch Protection
      run: echo 'Branch protection rules set'